CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO cities (id, name, "createdAt")
VALUES
(gen_random_uuid(), 'Adamantina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Adolfo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Aguaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Águas da Prata', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Águas de Lindóia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Águas de Santa Bárbara', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Águas de São Pedro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Agudos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Alambari', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Alfredo Marcondes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Altair', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Altinópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Alto Alegre', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Alumínio', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Álvares Florence', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Álvares Machado', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Álvaro de Carvalho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Alvinlândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Americana', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Américo Brasiliense', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Américo de Campos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Amparo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Analândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Andradina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Angatuba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Anhembi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Anhumas', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Aparecida', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Aparecida d''Oeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Apiaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Araçariguama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Araçatuba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Araçoiaba da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Aramina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Arandu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Arapeí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Araraquara', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Araras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Arco-Íris', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Arealva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Areias', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Areiópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ariranha', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Artur Nogueira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Arujá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Aspásia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Assis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Atibaia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Auriflama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Avaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Avanhandava', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Avaré', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bady Bassitt', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Balbinos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bálsamo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bananal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barão de Antonina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barbosa', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bariri', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barra Bonita', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barra do Chapéu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barra do Turvo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barretos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barrinha', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Barueri', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bastos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Batatais', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bauru', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bebedouro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bento de Abreu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bernardino de Campos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bertioga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bilac', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Birigui', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Biritiba Mirim', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Boa Esperança do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bocaina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bofete', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Boituva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bom Jesus dos Perdões', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bom Sucesso de Itararé', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Borá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Boracéia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Borborema', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Borebi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Botucatu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Bragança Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Braúna', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Brejo Alegre', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Brodowski', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Brotas', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Buri', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Buritama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Buritizal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cabrália Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cabreúva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Caçapava', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cachoeira Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Caconde', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cafelândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Caiabu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Caieiras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Caiuá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cajamar', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cajati', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cajobi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cajuru', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Campina do Monte Alegre', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Campinas', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Campo Limpo Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Campos do Jordão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Campos Novos Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cananéia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Canas', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cândido Mota', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cândido Rodrigues', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Canitar', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Capão Bonito', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Capela do Alto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Capivari', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Caraguatatuba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Carapicuíba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cardoso', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Casa Branca', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cássia dos Coqueiros', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Castilho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Catanduva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Catiguá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cedral', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cerqueira César', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cerquilho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cesário Lange', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Charqueada', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Chavantes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Clementina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Colina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Colômbia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Conchal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Conchas', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cordeirópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Coroados', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Coronel Macedo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Corumbataí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cosmópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cosmorama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cotia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cravinhos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cristais Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cruzália', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cruzeiro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cubatão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Cunha', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Descalvado', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Diadema', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Dirce Reis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Divinolândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Dobrada', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Dois Córregos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Dolcinópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Dourado', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Dracena', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Duartina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Dumont', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Echaporã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Eldorado', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Elias Fausto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Elisiário', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Embaúba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Embu das Artes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Embu-Guaçu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Emilianópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Engenheiro Coelho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Espírito Santo do Pinhal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Espírito Santo do Turvo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Estiva Gerbi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Estrela d''Oeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Estrela do Norte', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Euclides da Cunha Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Fartura', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Fernando Prestes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Fernandópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Fernão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ferraz de Vasconcelos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Flora Rica', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Floreal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Flórida Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Florínea', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Franca', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Francisco Morato', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Franco da Rocha', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Gabriel Monteiro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Gália', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Garça', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Gastão Vidigal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Gavião Peixoto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'General Salgado', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Getulina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Glicério', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guaiçara', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guaimbê', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guaíra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guapiaçu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guapiara', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guará', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guaraçaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guaraci', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guarani d''Oeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guarantã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guararapes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guararema', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guaratinguetá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guareí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guariba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guarujá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guarulhos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guatapará', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Guzolândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Herculândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Holambra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Hortolândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iacanga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iacri', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iaras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ibaté', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ibirá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ibirarema', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ibitinga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ibiúna', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Icém', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iepê', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Igaraçu do Tietê', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Igarapava', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Igaratá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iguape', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ilha Comprida', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ilha Solteira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ilhabela', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Indaiatuba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Indiana', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Indiaporã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Inúbia Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ipaussu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iperó', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ipeúna', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ipiguá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iporanga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ipuã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Iracemápolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Irapuã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Irapuru', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itaberá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itajobi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itaju', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itanhaém', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itaoca', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapecerica da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapetininga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapeva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapevi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapirapuã Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itápolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itaporanga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapuí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itapura', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itaquaquecetuba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itararé', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itariri', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itatiba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itatinga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itirapina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itirapuã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itobi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Itupeva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ituverava', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jaborandi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jaboticabal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jacareí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jaci', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jacupiranga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jaguariúna', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jales', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jambeiro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jandira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jardinópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jarinu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jaú', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jeriquara', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Joanópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'João Ramalho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'José Bonifácio', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Júlio Mesquita', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jumirim', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Jundiaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Junqueirópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Juquiá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Juquitiba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lagoinha', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Laranjal Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lavínia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lavrinhas', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Leme', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lençóis Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Limeira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lindóia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lins', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lorena', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lourdes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Louveira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lucélia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lucianópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Luís Antônio', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Luiziânia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lupércio', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lutécia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Macatuba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Macaubal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Macedônia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Magda', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mairinque', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mairiporã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Manduri', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Marabá Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Maracaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Marapoama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mariápolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Marília', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Marinópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Martinópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Matão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mauá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mendonça', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Meridiano', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mesópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Miguelópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mineiros do Tietê', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mira Estrela', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Miracatu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mirandópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mirante do Paranapanema', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mirassol', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mirassolândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mococa', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mogi das Cruzes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mogi Guaçu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mogi Mirim', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mombuca', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monções', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Mongaguá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monte Alegre do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monte Alto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monte Aprazível', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monte Azul Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monte Castelo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monte Mor', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Monteiro Lobato', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Morro Agudo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Morungaba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Motuca', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Murutinga do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nantes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Narandiba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Natividade da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nazaré Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Neves Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nhandeara', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nipoã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Aliança', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Campina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Canaã Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Castilho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Europa', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Granada', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Guataporanga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Independência', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Luzitânia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nova Odessa', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Novais', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Novo Horizonte', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Nuporanga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ocauçu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Óleo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Olímpia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Onda Verde', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Oriente', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Orindiúva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Orlândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Osasco', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Oscar Bressane', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Osvaldo Cruz', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ourinhos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ouro Verde', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ouroeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pacaembu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Palestina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Palmares Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Palmeira d''Oeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Palmital', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Panorama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paraguaçu Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paraibuna', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paraíso', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paranapanema', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paranapuã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Parapuã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pardinho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pariquera-Açu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Parisi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Patrocínio Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paulicéia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paulínia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paulistânia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Paulo de Faria', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pederneiras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pedra Bela', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pedranópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pedregulho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pedreira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pedrinhas Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pedro de Toledo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Penápolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pereira Barreto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pereiras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Peruíbe', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piacatu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piedade', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pilar do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pindamonhangaba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pindorama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pinhalzinho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piquerobi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piquete', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piracaia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piracicaba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piraju', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pirajuí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pirangi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pirapora do Bom Jesus', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pirapozinho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pirassununga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Piratininga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pitangueiras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Planalto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Platina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Poá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Poloni', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pompéia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pongaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pontal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pontalinda', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pontes Gestal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Populina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Porangaba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Porto Feliz', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Porto Ferreira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Potim', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Potirendaba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pracinha', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pradópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Praia Grande', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Pratânia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Presidente Alves', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Presidente Bernardes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Presidente Epitácio', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Presidente Prudente', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Presidente Venceslau', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Promissão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Quadra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Quatá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Queiroz', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Queluz', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Quintana', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rafard', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rancharia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Redenção da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Regente Feijó', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Reginópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Registro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Restinga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão Bonito', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão Branco', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão Corrente', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão dos Índios', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão Grande', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão Pires', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ribeirão Preto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rifaina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rincão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rinópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rio Claro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rio das Pedras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rio Grande da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Riolândia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Riversul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rosana', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Roseira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rubiácea', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Rubinéia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sabino', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sagres', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sales', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sales Oliveira', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Salesópolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Salmourão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Saltinho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Salto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Salto de Pirapora', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Salto Grande', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sandovalina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Adélia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Albertina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Bárbara d''Oeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Branca', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Clara d''Oeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Cruz da Conceição', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Cruz da Esperança', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Cruz das Palmeiras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Cruz do Rio Pardo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Ernestina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Fé do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Gertrudes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Isabel', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Lúcia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Maria da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Mercedes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Rita d''Oeste', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Rita do Passa Quatro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Rosa de Viterbo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santa Salete', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santana da Ponte Pensa', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santana de Parnaíba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo Anastácio', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo André', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo Antônio da Alegria', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo Antônio de Posse', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo Antônio do Aracanguá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo Antônio do Jardim', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo Antônio do Pinhal', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santo Expedito', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santópolis do Aguapeí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Santos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Bento do Sapucaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Bernardo do Campo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Caetano do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Carlos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Francisco', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São João da Boa Vista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São João das Duas Pontes', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São João de Iracema', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São João do Pau d''Alho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Joaquim da Barra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São José da Bela Vista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São José do Barreiro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São José do Rio Pardo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São José do Rio Preto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São José dos Campos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Lourenço da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Luiz do Paraitinga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Manuel', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Miguel Arcanjo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Paulo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Pedro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Pedro do Turvo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Roque', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Sebastião', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Sebastião da Grama', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Simão', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'São Vicente', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sarapuí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sarutaiá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sebastianópolis do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Serra Azul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Serra Negra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Serrana', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sertãozinho', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sete Barras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Severínia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Silveiras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Socorro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sorocaba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sud Mennucci', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Sumaré', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Suzanápolis', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Suzano', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tabapuã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tabatinga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taboão da Serra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taciba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taguaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taiaçu', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taiúva', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tambaú', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tanabi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tapiraí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tapiratiba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taquaral', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taquaritinga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taquarituba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taquarivaí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tarabai', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tarumã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tatuí', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Taubaté', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tejupá', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Teodoro Sampaio', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Terra Roxa', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tietê', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Timburi', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Torre de Pedra', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Torrinha', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Trabiju', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tremembé', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Três Fronteiras', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tuiuti', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tupã', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Tupi Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Turiúba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Turmalina', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ubarana', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ubatuba', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Ubirajara', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Uchoa', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'União Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Urânia', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Uru', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Urupês', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Valentim Gentil', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Valinhos', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Valparaíso', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Vargem', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Vargem Grande do Sul', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Vargem Grande Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Várzea Paulista', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Vera Cruz', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Vinhedo', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Viradouro', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Vista Alegre do Alto', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Vitória Brasil', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Votorantim', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Votuporanga', CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Zacarias', CURRENT_TIMESTAMP);
